version: "3.9"

services:
  mongo:
    image: mongo:7.0
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./_docker-data/mongo:/data/db
    env_file:
      - .env