basePath: /
definitions:
  controller.LoginOut:
    properties:
      message:
        type: string
      session:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: An API Documentation for Triva
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Triva - API Docs
  version: "2.0"
paths:
  /auth/login:
    post:
      description: Get auth session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.LoginOut'
      security:
      - securityDefinitions.apikey: []
      summary: Login to authenticated
      tags:
      - root
schemes:
- http
swagger: "2.0"
